/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */
export type GetUserSubscriptionsUsingGETParams = {
offset?: number;
pageNumber?: number;
pageSize?: number;
paged?: boolean;
'sort.sorted'?: boolean;
'sort.unsorted'?: boolean;
unpaged?: boolean;
};

export type GetUserLikedItemsUsingGETParams = {
offset?: number;
pageNumber?: number;
pageSize?: number;
paged?: boolean;
'sort.sorted'?: boolean;
'sort.unsorted'?: boolean;
unpaged?: boolean;
};

export type LoginUsingPOSTParams = {
/**
 * 리다이렉트 후 파싱한 access_token 값
 */
accessToken: string;
};

export type GetSubscriptionsUsingGETParams = {
/**
 * 검색 키워드, required = false
 */
keyword?: string;
offset?: number;
pageNumber?: number;
pageSize?: number;
paged?: boolean;
'sort.sorted'?: boolean;
'sort.unsorted'?: boolean;
unpaged?: boolean;
};

export type CheckHealthUsingGET200 = { [key: string]: any };

export type GetLikesUsingGETParams = {
/**
 * 검색 키워드, required = false
 */
keyword?: string;
offset?: number;
pageNumber?: number;
pageSize?: number;
paged?: boolean;
'sort.sorted'?: boolean;
'sort.unsorted'?: boolean;
unpaged?: boolean;
};

export type GetItemsOfSubscribedChannelUsingGETParams = {
offset?: number;
pageNumber?: number;
pageSize?: number;
paged?: boolean;
'sort.sorted'?: boolean;
'sort.unsorted'?: boolean;
unpaged?: boolean;
};

export type GetItemsUsingGETParams = {
offset?: number;
pageNumber?: number;
pageSize?: number;
paged?: boolean;
'sort.sorted'?: boolean;
'sort.unsorted'?: boolean;
unpaged?: boolean;
};

export type GetChannelPreviewViaRssFeedUsingGETParams = {
/**
 * 블로그 홈 주소
 */
homeUrl: string;
/**
 * 확인할 RSS Feed 주소
 */
rssFeedUrl: string;
};

export type GetChannelPreviewUsingGETParams = {
/**
 * 확인할 주소
 */
url: string;
};

export interface UserSubscribedChannelDTO {
  description?: string;
  feedUrl?: string;
  id?: number;
  imageUrl?: string;
  isSubscribed?: boolean;
  title?: string;
  url?: string;
}

export interface UserSubscriptionListResponse {
  channels?: UserSubscribedChannelDTO[];
  next?: number;
  prev?: number;
  totalCount?: number;
}

export interface UserItemDTO {
  channelId?: number;
  channelImageUrl?: string;
  channelTitle?: string;
  description?: string;
  guid?: string;
  id?: number;
  imageUrl?: string;
  isLiked?: boolean;
  isViewed?: boolean;
  link?: string;
  publishedAt?: string;
  title?: string;
}

export interface UserItemListResponse {
  items?: UserItemDTO[];
  next?: number;
  prev?: number;
  totalCount?: number;
}

export interface UserInfoResponse {
  /** 계정에 등록된 이메일 */
  email?: string;
  /** 계정에 등록된 이름 */
  name?: string;
  /** 프로필 이미지 URL */
  profileImageUrl?: string;
  /** 유저네임 */
  username?: string;
}

export interface TokenReissueResponse {
  /** 액세스 토큰 */
  accessToken?: string;
  /** 리프레쉬 토큰 */
  refreshToken?: string;
}

export interface TokenReissueRequest {
  /** 리프레쉬 토큰 */
  refreshToken?: string;
}

export interface SubscriptionListResponse {
  channels?: ChannelDetailsDTO[];
  next?: number;
  prev?: number;
  totalCount?: number;
}

export interface RecommendedItemListResponse {
  items?: ItemDetailsDTO[];
}

export interface RecommendedChannelListResponse {
  channels?: ChannelDetailsDTO[];
}

export interface PublicUserInfoResponse {
  /** 계정에 등록된 이름 */
  name?: string;
  /** 프로필 이미지 URL */
  profileImageUrl?: string;
  /** 유저네임 */
  username?: string;
}

export interface PublicItemListResponse {
  channel?: ChannelDetailsDTO;
  items?: ItemDetailsDTO[];
  next?: number;
  prev?: number;
  totalCount?: number;
}

export interface LikeResponse {
  isLiked?: boolean;
  itemId?: number;
}

export interface ItemViewResponse {
  /** 아이템 ID */
  id?: number;
  /** 읽음 여부 (T/F) */
  isViewed?: boolean;
}

export interface ItemDetailsDTO {
  channelId?: number;
  channelImageUrl?: string;
  channelTitle?: string;
  description?: string;
  guid?: string;
  id?: number;
  imageUrl?: string;
  isLiked?: boolean;
  isViewed?: boolean;
  link?: string;
  publishedAt?: string;
  title?: string;
}

export interface GoogleLoginResponse {
  /** 액세스 토큰 */
  accessToken?: string;
  /** 이메일 */
  email?: string;
  /** 이름 */
  name?: string;
  /** 프로필 이미지 url */
  profileImageUrl?: string;
  /** 리프레쉬 토큰 */
  refreshToken?: string;
  /** 유저네임 */
  username?: string;
}

export interface ChannelRegisterResponse {
  /** 등록 일시 */
  createdAt?: string;
  /** RSS 피드 주소 */
  feedUrl?: string;
  /** 채널 ID */
  id?: number;
  /** 채널 이미지 url */
  imageUrl?: string;
  /** 채널 제목 */
  title?: string;
  /** 블로그 홈 주소 */
  url?: string;
}

export interface ChannelRegisterRequest {
  /** 등록할 RSS Feed URL */
  feedUrl?: string;
  /** 기존 홈 주소 */
  url?: string;
}

export interface ChannelPreviewResponse {
  /** 채널 설명 */
  description?: string;
  /** RSS Feed 주소 */
  feedUrl?: string;
  /** 채널 이미지 URL */
  imageUrl?: string;
  /** 채널 제목 */
  title?: string;
  /** 블로그 홈 주소 */
  url?: string;
}

export interface ChannelDetailsDTO {
  description?: string;
  feedUrl?: string;
  id?: number;
  imageUrl?: string;
  isSubscribed?: boolean;
  title?: string;
  url?: string;
}

