/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */
export type GetUserSubscriptionsUsingGETParams = {
/**
 * 페이지 번호
 */
page: number;
/**
 * 페이지당 항목 개수
 */
size: number;
};

export type GetUserLikedItemsUsingGETParams = {
/**
 * 페이지 번호
 */
page: number;
/**
 * 페이지당 항목 개수
 */
size: number;
};

export type LoginUsingPOSTParams = {
/**
 * 리다이렉트 후 파싱한 access_token 값
 */
accessToken: string;
};

export type GetSubscriptionsUsingGETParams = {
/**
 * 검색 키워드, required = false
 */
keyword?: string;
/**
 * 페이지 번호
 */
page: number;
/**
 * 페이지당 항목 개수
 */
size: number;
};

export type CheckHealthUsingGET200 = { [key: string]: any };

export type GetLikesUsingGETParams = {
/**
 * 검색 키워드, required = false
 */
keyword?: string;
/**
 * 페이지 번호
 */
page: number;
/**
 * 페이지당 항목 개수
 */
size: number;
};

export type GetItemsOfSubscribedChannelUsingGETParams = {
/**
 * 페이지 번호
 */
page: number;
/**
 * 페이지당 항목 개수
 */
size: number;
};

export type GetItemsUsingGETParams = {
/**
 * 페이지 번호
 */
page: number;
/**
 * 페이지당 항목 개수
 */
size: number;
};

export type GetChannelPreviewViaRssFeedUsingGETParams = {
/**
 * 블로그 홈 주소
 */
homeUrl: string;
/**
 * 확인할 RSS Feed 주소
 */
rssFeedUrl: string;
};

export type GetChannelPreviewUsingGETParams = {
/**
 * 확인할 주소
 */
url: string;
};

export interface UserSubscribedChannelDTO {
  /** 채널 설명 */
  description: string;
  /** RSS Feed 주소 */
  feedUrl: string;
  /** 채널 ID */
  id: number;
  /** 채널 이미지 URL */
  imageUrl: string;
  /** 구독 여부 (T/F) */
  isSubscribed: boolean;
  /** 채널 제목 */
  title: string;
  /** 블로그 홈 주소 */
  url: string;
}

export interface UserSubscriptionListResponse {
  /** 채널 목록 */
  channels: UserSubscribedChannelDTO[];
  /** 다음 페이지 번호 */
  next: number;
  /** 이전 페이지 번호 */
  prev: number;
  /** 총 채널 개수 */
  totalCount: number;
}

export interface UserItemDTO {
  /** 채널 ID */
  channelId: number;
  /** 채널 이미지 URL */
  channelImageUrl: string;
  /** 채널 제목 */
  channelTitle: string;
  /** 아이템 본문 내용 */
  description: string;
  /** guid */
  guid: string;
  /** 아이템 ID */
  id: number;
  /** 아이템 이미지 URL */
  imageUrl: string;
  /** 좋아요(보관) 여부 (T/F) */
  isLiked: boolean;
  /** 읽음 여부 (T/F) */
  isViewed: boolean;
  /** link */
  link: string;
  /** 아이템 발행 일자 */
  publishedAt: string;
  /** 아이템 제목 */
  title: string;
}

export interface UserItemListResponse {
  /** 아이템 목록 */
  items: UserItemDTO[];
  /** 다음 페이지 번호 */
  next: number;
  /** 이전 페이지 번호 */
  prev: number;
  /** 총 아이템 개수 */
  totalCount: number;
}

export interface UserInfoResponse {
  /** 계정에 등록된 이메일 */
  email: string;
  /** 계정에 등록된 이름 */
  name: string;
  /** 프로필 이미지 URL */
  profileImageUrl: string;
  /** 유저네임 */
  username: string;
}

export interface TokenReissueResponse {
  /** 액세스 토큰 */
  accessToken: string;
  /** 리프레쉬 토큰 */
  refreshToken: string;
}

export interface TokenReissueRequest {
  /** 리프레쉬 토큰 */
  refreshToken?: string;
}

export interface SubscriptionListResponse {
  /** 채널 목록 */
  channels: ChannelDetailsDTO[];
  /** 다음 페이지 번호 */
  next: number;
  /** 이전 페이지 번호 */
  prev: number;
  /** 총 채널 개수 */
  totalCount: number;
}

export interface RecommendedItemListResponse {
  /** 아이템 목록 */
  items: ItemDetailsDTO[];
}

export interface RecommendedChannelListResponse {
  /** 채널 목록 */
  channels: ChannelDetailsDTO[];
}

export interface PublicUserInfoResponse {
  /** 계정에 등록된 이름 */
  name: string;
  /** 프로필 이미지 URL */
  profileImageUrl: string;
  /** 유저네임 */
  username: string;
}

export interface PublicItemListResponse {
  /** 채널 정보 */
  channel: ChannelDetailsDTO;
  /** 아이템 목록 */
  items: ItemDetailsDTO[];
  /** 다음 페이지 번호 */
  next: number;
  /** 이전 페이지 번호 */
  prev: number;
  /** 총 아이템 개수 */
  totalCount: number;
}

export interface LikeResponse {
  /** 좋아요(보관) 여부 (T/F) */
  isLiked: boolean;
  /** 아이템 ID */
  itemId: number;
}

export interface ItemViewResponse {
  /** 아이템 ID */
  id: number;
  /** 읽음 여부 (T/F) */
  isViewed: boolean;
}

export interface ItemDetailsDTO {
  /** 채널 ID */
  channelId: number;
  /** 채널 이미지 URL */
  channelImageUrl: string;
  /** 채널 제목 */
  channelTitle: string;
  /** 아이템 본문 내용 */
  description: string;
  /** guid */
  guid: string;
  /** 아이템 ID */
  id: number;
  /** 아이템 이미지 URL */
  imageUrl: string;
  /** 좋아요(보관) 여부 (T/F) */
  isLiked: boolean;
  /** 읽음 여부 (T/F) */
  isViewed: boolean;
  /** link */
  link: string;
  /** 아이템 발행 일자 */
  publishedAt: string;
  /** 아이템 제목 */
  title: string;
}

export interface GoogleLoginResponse {
  /** 액세스 토큰 */
  accessToken: string;
  /** 이메일 */
  email: string;
  /** 이름 */
  name: string;
  /** 프로필 이미지 url */
  profileImageUrl: string;
  /** 리프레쉬 토큰 */
  refreshToken: string;
  /** 유저네임 */
  username: string;
}

export interface ChannelRegisterResponse {
  /** 등록 일시 */
  createdAt: string;
  /** RSS 피드 주소 */
  feedUrl: string;
  /** 채널 ID */
  id: number;
  /** 채널 이미지 url */
  imageUrl: string;
  /** 채널 제목 */
  title: string;
  /** 블로그 홈 주소 */
  url: string;
}

export interface ChannelRegisterRequest {
  /** 등록할 RSS Feed URL */
  feedUrl?: string;
  /** 기존 홈 주소 */
  url?: string;
}

export interface ChannelPreviewResponse {
  /** 채널 설명 */
  description: string;
  /** RSS Feed 주소 */
  feedUrl: string;
  /** 채널 이미지 URL */
  imageUrl: string;
  /** 채널 제목 */
  title: string;
  /** 블로그 홈 주소 */
  url: string;
}

export interface ChannelDetailsDTO {
  /** 채널 설명 */
  description: string;
  /** RSS Feed 주소 */
  feedUrl: string;
  /** 채널 ID */
  id: number;
  /** 채널 이미지 URL */
  imageUrl: string;
  /** 구독 여부 (T/F) */
  isSubscribed: boolean;
  /** 채널 제목 */
  title: string;
  /** 블로그 홈 주소 */
  url: string;
}

