/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */
import type {
  ChannelPreviewResponse,
  ChannelRegisterRequest,
  ChannelRegisterResponse,
  GetChannelPreviewUsingGETParams,
  GetChannelPreviewViaRssFeedUsingGETParams,
  RecommendedChannelListResponse
} from './apiDocumentation.schemas'
import { feedoongApi } from '../../api/index';




  /**
 * @summary 채널(RSS 피드 주소) 등록
 */
export const registerChannelUsingPOST = (
    channelRegisterRequest: ChannelRegisterRequest,
 ) => {
      return feedoongApi<ChannelRegisterResponse>(
      {url: `/v1/channels`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: channelRegisterRequest
    },
      );
    }
  /**
 * @summary RSS 피드 정보 확인 (블로그 링크로 등록)
 */
export const getChannelPreviewUsingGET = (
    params: GetChannelPreviewUsingGETParams,
 ) => {
      return feedoongApi<ChannelPreviewResponse>(
      {url: `/v1/channels/preview`, method: 'get',
        params
    },
      );
    }
  /**
 * @summary RSS 피드 정보 확인 (RSS Feed 주소 직접 등록)
 */
export const getChannelPreviewViaRssFeedUsingGET = (
    params: GetChannelPreviewViaRssFeedUsingGETParams,
 ) => {
      return feedoongApi<ChannelPreviewResponse>(
      {url: `/v1/channels/preview/rss`, method: 'get',
        params
    },
      );
    }
  /**
 * @summary 채널 둘러보기
 */
export const getRecommendedChannelsUsingGET = (
    
 ) => {
      return feedoongApi<RecommendedChannelListResponse>(
      {url: `/v1/channels/recommended`, method: 'get'
    },
      );
    }
  