/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */
import type {
  GetItemsOfSubscribedChannelUsingGETParams,
  GetItemsUsingGETParams,
  GetLikesUsingGETParams,
  ItemViewResponse,
  PublicItemListResponse,
  RecommendedItemListResponse,
  UserItemListResponse
} from './apiDocumentation.schemas'
import { feedoongApi } from '../../api/index';




  /**
 * @summary 구독한 채널들의 아이템 리스트
 */
export const getItemsUsingGET = (
    params: GetItemsUsingGETParams,
 ) => {
      return feedoongApi<UserItemListResponse>(
      {url: `/v1/items`, method: 'get',
        params
    },
      );
    }
  /**
 * @summary 구독한 채널마다의 아이템 리스트
 */
export const getItemsOfSubscribedChannelUsingGET = (
    channelId: number,
    params: GetItemsOfSubscribedChannelUsingGETParams,
 ) => {
      return feedoongApi<PublicItemListResponse>(
      {url: `/v1/items/channel/${channelId}`, method: 'get',
        params
    },
      );
    }
  /**
 * @summary 보관(좋아요)한 아이템 리스트
 */
export const getLikesUsingGET = (
    params: GetLikesUsingGETParams,
 ) => {
      return feedoongApi<UserItemListResponse>(
      {url: `/v1/items/liked`, method: 'get',
        params
    },
      );
    }
  /**
 * @summary 아이템 둘러보기
 */
export const getRecommendedItemsUsingGET = (
    
 ) => {
      return feedoongApi<RecommendedItemListResponse>(
      {url: `/v1/items/recommended`, method: 'get'
    },
      );
    }
  /**
 * @summary 아이템 읽음 처리
 */
export const viewItemUsingPOST = (
    itemId: number,
 ) => {
      return feedoongApi<ItemViewResponse>(
      {url: `/v1/items/view/${itemId}`, method: 'post'
    },
      );
    }
  