/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */
import type {
  LikeResponse
} from './apiDocumentation.schemas'
// import { feedoongApi } from '../../api/index';
import { feedoongApi } from '../../api/feedoongApi'




  /**
 * @summary 아이템 보관(좋아요)
 */
export const likeUsingPOST = (
    itemId: number,
 ) => {
      return feedoongApi<LikeResponse>(
      {url: `/v1/likes/${itemId}`, method: 'post'
    },
      );
    }
  /**
 * @summary 아이템 보관(좋아요) 취소
 */
export const unlikeUsingDELETE = (
    itemId: number,
 ) => {
      return feedoongApi<LikeResponse>(
      {url: `/v1/likes/${itemId}`, method: 'delete'
    },
      );
    }
  