/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */
import type {
  CheckHealthUsingGET200
} from './apiDocumentation.schemas'
// import { feedoongApi } from '../../api/index';
import { feedoongApi } from '../../api/feedoongApi'




  /**
 * @summary checkHealth
 */
export const checkHealthUsingGET = (
    
 ) => {
      return feedoongApi<CheckHealthUsingGET200>(
      {url: `/v1/status/health`, method: 'get'
    },
      );
    }
  export type CheckHealthUsingGETResult = NonNullable<Awaited<ReturnType<typeof checkHealthUsingGET>>>
