/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */
import type {
  GetSubscriptionsUsingGETParams,
  SubscriptionListResponse
} from './apiDocumentation.schemas'
import { feedoongApi } from '../../api/index';




  /**
 * @summary 자신이 구독한 채널 리스트 확인
 */
export const getSubscriptionsUsingGET = (
    params?: GetSubscriptionsUsingGETParams,
 ) => {
      return feedoongApi<SubscriptionListResponse>(
      {url: `/v1/subscriptions`, method: 'get',
        params
    },
      );
    }
  /**
 * @summary 채널 구독 취소
 */
export const unsubscribeUsingDELETE = (
    channelId: number,
 ) => {
      return feedoongApi<void>(
      {url: `/v1/subscriptions/${channelId}`, method: 'delete'
    },
      );
    }
  