/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Api Documentation
 * Api Documentation
 * OpenAPI spec version: 1.0
 */
import type {
  GetUserLikedItemsUsingGETParams,
  GetUserSubscriptionsUsingGETParams,
  GoogleLoginResponse,
  LoginUsingPOSTParams,
  PublicUserInfoResponse,
  TokenReissueRequest,
  TokenReissueResponse,
  UserInfoResponse,
  UserItemListResponse,
  UserSubscriptionListResponse
} from './apiDocumentation.schemas'
import { feedoongApi } from '../../api/index';




  /**
 * @summary 계정 탈퇴
 */
export const deactivateUserUsingDELETE = (
    
 ) => {
      return feedoongApi<void>(
      {url: `/v1/users`, method: 'delete'
    },
      );
    }
  /**
 * @summary 구글 로그인
 */
export const loginUsingPOST = (
    params: LoginUsingPOSTParams,
 ) => {
      return feedoongApi<GoogleLoginResponse>(
      {url: `/v1/users/login/google`, method: 'post',
        params
    },
      );
    }
  /**
 * @summary 회원 정보 확인
 */
export const getUserInfoUsingGET = (
    
 ) => {
      return feedoongApi<UserInfoResponse>(
      {url: `/v1/users/me`, method: 'get'
    },
      );
    }
  /**
 * @summary 액세스 토큰 재발급
 */
export const reissueTokenUsingPOST = (
    tokenReissueRequest: TokenReissueRequest,
 ) => {
      return feedoongApi<TokenReissueResponse>(
      {url: `/v1/users/token`, method: 'post',
      headers: {'Content-Type': 'application/json', },
      data: tokenReissueRequest
    },
      );
    }
  /**
 * @summary 특정 유저 정보 확인
 */
export const getPublicUserInfoUsingGET = (
    username: string,
 ) => {
      return feedoongApi<PublicUserInfoResponse>(
      {url: `/v1/users/${username}/info`, method: 'get'
    },
      );
    }
  /**
 * @summary 특정 유저가 저장한 게시글 리스트 확인
 */
export const getUserLikedItemsUsingGET = (
    username: string,
    params?: GetUserLikedItemsUsingGETParams,
 ) => {
      return feedoongApi<UserItemListResponse>(
      {url: `/v1/users/${username}/liked-items`, method: 'get',
        params
    },
      );
    }
  /**
 * @summary 특정 유저가 구독한 채널 리스트 확인
 */
export const getUserSubscriptionsUsingGET = (
    username: string,
    params?: GetUserSubscriptionsUsingGETParams,
 ) => {
      return feedoongApi<UserSubscriptionListResponse>(
      {url: `/v1/users/${username}/subscriptions`, method: 'get',
        params
    },
      );
    }
  